# Generated by Django 2.2.2 on 2021-02-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category_name', models.CharField(max_length=150)),
                ('subcategory_name', models.CharField(max_length=150)),
                ('level', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('real_price', models.IntegerField(default=5)),
                ('discount', models.IntegerField(default=30)),
                ('course_score', models.FloatField(default=3.5)),
                ('users', models.IntegerField(default=0)),
            ],
        ),
    ]
