# Generated by Django 2.2.2 on 2021-02-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210224_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category_name',
            field=models.CharField(choices=[('marketing_digital', 'Marketing Digital'), ('manualidades', 'Manualidades'), ('ilustraciones_dibujo', 'Ilustraciones y Dibujo'), ('lifestyle', 'Lifestyle'), ('video', 'Video'), ('negocios', 'Negocios'), ('fotografia', 'Fotografía'), ('diseño', 'Diseño'), ('escritura', 'Escritura'), ('animacion_3D', 'Animación & 3D')], max_length=150),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('avanzado', 'Avanzado'), ('Introductorio', 'Introductorio'), ('completo', 'Completo'), ('intermedio', 'Intermedio')], max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='subcategory_name',
            field=models.CharField(choices=[('marketing_digital', 'Marketing Digital'), ('bordado_costura', 'Bordado y costura'), ('ilustraciones_digital', 'Ilustraciones Digital'), ('lifestyle', 'Lifestyle'), ('produccion', 'Producción'), ('video', 'Video'), ('diseño', 'Diseño'), ('locucion', 'Locución'), ('escritura', 'Escritura'), ('animacion_2D', 'Animación 2D'), ('innovacion', 'Innovación'), ('liderazgo', 'Liderazgo'), ('fundamentos_fotografia', 'Fundamentos de fotografia'), ('publicidad', 'Publicidad'), ('postproduccion', 'Postroduccion'), ('dibujo', 'Dibujo'), ('branding', 'Branding'), ('retoque_fotografico', 'Retoque Fotográfico'), ('data', 'Data'), ('ventas', 'Ventas')], max_length=150),
        ),
    ]
